const ROUTES_META = {
  signUp: "/sign-up",
  logIn: "/login",
  dashBoard: "/dashboard",
  admin: "/admin",
  faq: "/faq",
  bookNow: "/booknow",
  freeServices: "/freeservices",
  appointmentSlot: "/appointmentslot",
  reviews: "/customerreviews",
  blogs: "/blogs",
  services: "/services",
  workShop: "/workshop",
  profile: "/profile",
  estimate: "estimate",
  adminJobs: "/jobs",
  adminUsers: "/users",
  adminCallback: "/callback",
  adminBooked: "/bookedSessions",
  adminAddJob: "/addJob",
};
export default ROUTES_META;
