import { CarBrand } from "../interfaces/car";

export function getBrands(): CarBrand[] {
    return [
        {
            name: "Hyundai",
            id: "hyunai",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-7.jpeg",
            models: [
                {
                    name: "grand i10",
                    id: "grand i10",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "grand i10 nios",
                    id: "grand i10 nios",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "XCENT",
                    id: "XCENT",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ACCENT",
                    id: "ACCENT",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                { name: "i10", id: "i10", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "SANTRO ms",
                    id: "SANTRO ms",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                {
                    name: "SANTRO xing",
                    id: "SANTRO xing",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                {
                    name: "SANTRO",
                    id: "SANTRO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                {
                    name: "I 20",
                    id: "I 20",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "CRETA",
                    id: "CRETA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "SANTA FE",
                    id: "SANTA FE",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "EON", id: "EON", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "VERNA 1.6",
                    id: "VERNA 1.6",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                {
                    name: "VERNA 1.5",
                    id: "VERNA 1.5",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "VERNA 1.4 vvt",
                    id: "VERNA 1.4 vvt",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                {
                    name: "VERNA 1.6 vvt",
                    id: "VERNA 1.6 vvt",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "VERNA 1.4 turbo",
                    id: "VERNA 1.4 turbo",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                {
                    name: "VERNA 1.6 turbo",
                    id: "VERNA 1.6 turbo",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "VERNA",
                    id: "VERNA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "VERNA 1.0",
                    id: "VERNA 1.0",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                {
                    name: "Avante",
                    id: "Avante",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ELANTRA",
                    id: "ELANTRA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "VENUE",
                    id: "VENUE",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "TUCSON",
                    id: "TUCSON",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "SONATA",
                    id: "SONATA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "GETZ",
                    id: "GETZ",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "AURA",
                    id: "AURA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
            ],
        },
        {
            name: "Kia Motors",
            id: "kiamotors",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-38.jpeg",
            models: [
                {
                    name: "sonet",
                    id: "sonet",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "Seltos",
                    id: "Seltos",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "Carnival",
                    id: "Carnival",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
            ],
        },
        {
            name: "Maruti",
            id: "Maruti",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-9.jpeg",
            models: [
                {
                    name: "SWIFT",
                    id: "SWIFT",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "WAGON", id: "WAGON", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "BALENO",
                    id: "BALENO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "ALTO", id: "ALTO", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "RITZ",
                    id: "RITZ",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "CELERIO",
                    id: "CELERIO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "CIAZ",
                    id: "CIAZ",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ERTIGA",
                    id: "ERTIGA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "BREZZA",
                    id: "BREZZA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "ZEN", id: "ZEN", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "SX4",
                    id: "SX4",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "M", id: "M", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                { name: "A", id: "A", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "IGNIS",
                    id: "IGNIS",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "S",
                    id: "S",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "EECO", id: "EECO", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "ESTEEM",
                    id: "ESTEEM",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                { name: "OMNI", id: "OMNI", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "GRAND",
                    id: "GRAND",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "GYPSY",
                    id: "GYPSY",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "KIZASHI",
                    id: "KIZASHI",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "VERSA", id: "VERSA", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "XL6",
                    id: "XL6",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
            ],
        },
        {
            name: "Chevrolet",
            id: "chevrolet",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-1.jpeg",
            models: [
                {
                    name: "BEAT",
                    id: "BEAT",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "SAPRK", id: "SAPRK", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "CRUZE",
                    id: "CRUZE",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "AVEO",
                    id: "AVEO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "SAIL",
                    id: "SAIL",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ENJOY",
                    id: "ENJOY",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "UVA",
                    id: "UVA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "OPTRA",
                    id: "OPTRA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "TAVERA",
                    id: "TAVERA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "CAPTIVA",
                    id: "CAPTIVA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "FORESTOR",
                    id: "FORESTOR",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "TRAIBLAZER",
                    id: "TRAIBLAZER",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
            ],
        },
        {
            name: "Mahindra",
            id: "mahindra",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-8.jpeg",
            models: [
                {
                    name: "XUV",
                    id: "XUV",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "SCOPRIO",
                    id: "SCOPRIO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "KUV",
                    id: "KUV",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                { name: "XYLO", id: "XYLO", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["diesel"] },
                { name: "TUV", id: "TUV", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["diesel"] },
                {
                    name: "QUANTO",
                    id: "QUANTO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "BOLERO",
                    id: "BOLERO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "LOGAN",
                    id: "LOGAN",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "VERITO",
                    id: "VERITO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                { name: "THAR", id: "THAR", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["diesel"] },
                {
                    name: "NUVO",
                    id: "NUVO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "MARAZZO",
                    id: "MARAZZO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
            ],
        },
        {
            name: "Ford",
            id: "ford",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-5.jpeg",
            models: [
                {
                    name: "FIGO",
                    id: "FIGO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ECO",
                    id: "ECO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "FIESTA",
                    id: "FIESTA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "IKON",
                    id: "IKON",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ENDAVOUR",
                    id: "ENDAVOUR",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "FREESTYLE",
                    id: "FREESTYLE",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "FUSION",
                    id: "FUSION",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ESCORT",
                    id: "ESCORT",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "MANDEO",
                    id: "MANDEO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "MUSTANG",
                    id: "MUSTANG",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
            ],
        },
        {
            name: "Fiat",
            id: "fiat",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-4.jpeg",
            models: [
                {
                    name: "PUNTO",
                    id: "PUNTO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "LINEA",
                    id: "LINEA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "PALIO",
                    id: "PALIO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "AVVENTURA",
                    id: "AVVENTURA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ADVENTURE",
                    id: "ADVENTURE",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ABARTH",
                    id: "ABARTH",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "URBAN",
                    id: "URBAN",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "UNO",
                    id: "UNO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "PETRA",
                    id: "PETRA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
            ],
        },
        {
            name: "Toyota",
            id: "toyota",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-15.jpeg",
            models: [
                {
                    name: "ETIOS",
                    id: "ETIOS",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "INNOVA",
                    id: "INNOVA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "COROLLA",
                    id: "COROLLA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "FORTUNER",
                    id: "FORTUNER",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "QUALIS",
                    id: "QUALIS",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                { name: "YARIS", id: "YARIS", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                { name: "CAMRY", id: "CAMRY", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "GLANZA",
                    id: "GLANZA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "LAND",
                    id: "LAND",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
            ],
        },
        {
            name: "Volkswagen",
            id: "volkswagen",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-16.jpeg",
            models: [
                {
                    name: "POLO",
                    id: "POLO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "VENT",
                    id: "VENT",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "AMEO",
                    id: "AMEO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "CROSS",
                    id: "CROSS",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "JETTA",
                    id: "JETTA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "PASSAT",
                    id: "PASSAT",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "BEETLE",
                    id: "BEETLE",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                {
                    name: "TIGUAN",
                    id: "TIGUAN",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
            ],
        },
        {
            name: "Skoda",
            id: "skoda",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-13.jpeg",
            models: [
                {
                    name: "RAPID",
                    id: "RAPID",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "FABIA",
                    id: "FABIA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "SUPERB",
                    id: "SUPERB",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "LAURA",
                    id: "LAURA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "OCTAVIA",
                    id: "OCTAVIA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "YETI",
                    id: "YETI",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "KODIAQ",
                    id: "KODIAQ",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
            ],
        },
        {
            name: "Tata",
            id: "tata",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-14.jpeg",
            models: [
                {
                    name: "TIAGO",
                    id: "TIAGO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "NANO", id: "NANO", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["petrol"] },
                {
                    name: "ZEST",
                    id: "ZEST",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "NEXON",
                    id: "NEXON",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "INDICA",
                    id: "INDICA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "TIGOR",
                    id: "TIGOR",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "MANZA",
                    id: "MANZA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "INDIGO",
                    id: "INDIGO",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "SAFARI",
                    id: "SAFARI",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "BOLT",
                    id: "BOLT",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ALTROZ",
                    id: "ALTROZ",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "ARIA",
                    id: "ARIA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "HARRIER",
                    id: "HARRIER",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                {
                    name: "HEXA",
                    id: "HEXA",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "SUMO", id: "SUMO", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["diesel"] },
                {
                    name: "VENTURE",
                    id: "VENTURE",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
                {
                    name: "WINGER",
                    id: "WINGER",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol"],
                },
                { name: "XENON", id: "XENON", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["diesel"] },
            ],
        },
        {
            name: "MG",
            id: "mg",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-37.jpeg",
            models: [
                {
                    name: "Hector",
                    id: "Hector",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
                { name: "ZS-EV", id: "ZS-EV", imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg", type: ["diesel"] },
                {
                    name: "Gloster",
                    id: "Gloster",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel"],
                },
            ],
        },
        {
            name: "Honda",
            id: "honda",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
            models: [
                {
                    name: "City",
                    id: "City",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "Jazz",
                    id: "Jazz",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "Amaze",
                    id: "Amaze",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "WR-V",
                    id: "WR-V",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "Accord",
                    id: "Accord",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "CR-V",
                    id: "CR-V",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "Civic",
                    id: "Civic",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "Brio",
                    id: "Brio",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "Mobilio",
                    id: "Mobilio",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
                {
                    name: "BR-V",
                    id: "BR-V",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["diesel", "petrol"],
                },
            ],
        },
        {
            name: "HINDUSTAN MOTORS",
            id: "HINDUSTANMOTORS",
            imageURL:
                "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-33.jpeg",
            models: [
                {
                    name: "Ambassador",
                    id: "Ambassador",
                    imageURL: "https://gm-retail-app.s3.ap-south-1.amazonaws.com/thumbnails/brand-6.jpeg",
                    type: ["petrol", "diesel"],
                },
            ],
        },
    ];
}
